/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

/-! # Reflection 615 — token adjacency is a proxy, and virtual structure breaks it

A scanner guard often wants to say *"these two things belong to the same
syntactic unit"*, and the cheapest thing at hand is **token adjacency**: token
`b` came directly after token `a`, so they are part of one construct.

That proxy is exact only where **the grammar emits a token for every structural
boundary**.  Where a boundary can open *virtually* — an indent, a scope, an
implicit block — two adjacent tokens can belong to different units, and every
"no legal document has X directly after Y" argument built on adjacency is false
there.  The fix is not to abandon the proxy but to **gate the guard on the
context in which no virtual opening is possible**.

## The two halves

**§2, soundness where the proxy holds.** `adjacency_exact_without_virtual_open`:
for every document built without a virtual open, two property tokens are never
adjacent.  So inside a flow collection, adjacency really does mean "one node's
property run", and a guard may reject on it.

**§3, the counterexample where it does not.**
`adjacency_fires_on_a_legal_document`: `proppedBlock propped` — a property on a
collection that itself opens virtually, containing a node that carries its own
property — is a perfectly legal document whose token stream *is*
`[prop, prop, content]`.  The ungated guard rejects it.

## The method half (§4)

The counterexample was not in the hand-built probe list, and the reference
implementation agreed with the over-strict guard on every input that list
contained.  Both facts have the same structural cause, and it is not bad luck:
**a probe list written while thinking about a guard inherits the guard's own
blind spot.**  Here every hand-written case was flow-shaped, so
`handProbe_is_silent` is forced — `handProbe_has_no_virtual_open` proves the
list could not have refuted anything.  The **existing regression corpus** —
which contains shapes nobody was thinking about — is what refuted it:
`corpus_refutes_the_ungated_guard`.

Cheapest order, then: build the strictening, run the corpus you already compile,
*then* reason further.  A soundness argument of the form "no legal document has
X adjacent to Y" is a claim about the whole corpus, so the corpus, not a fresh
probe, is its natural refuter.

L4YAML DOCS item 9e, 2026-08-07.  `scanNextToken_dispatchContent` gained a
§6.9 [96] property-run check (`&a &b`, `!t !u`, `&a !t &b` and `&a *x` all
scanned clean in both pipelines, with no derivation).  The first version was
ungated and rejected two yaml-test-suite documents — 26DV's
`top3: &node3 ⏎  *alias1 : scalar3` and `&mapping⏎&key [ &item a, b, c ]: value`
— in which the anchor sits on a *block collection* that opens with a virtual
indent.  Gating the three tests on `s.inFlow` restored both while keeping every
flow-context rejection.  See `Tests/Guards/Proofs/ScannerFlowPropertyRun.lean`.
-/

namespace Tests.Reflections.AdjacencyProxyAndVirtualStructure

/-! ## §1  A document model in which some openings emit a token and some do not -/

/-- Scanner output alphabet.  `openFlowT` is the only *collection opening* that
    reaches the token stream; a block collection opens with a virtual indent and
    emits nothing (L4YAML's `blockMappingStart` is generated by the indent
    tracker, not by a character, and is filtered before the guard reads back). -/
inductive Tok where
  /-- `&a` or `!t` — a node property. -/
  | propT
  /-- A scalar. -/
  | contentT
  /-- `[` or `{`. -/
  | openFlowT
  deriving DecidableEq, Repr

/-- A **legal** document.  The type is the legality oracle: every inhabitant is
    a well-formed document, so a theorem quantified over `Node` is a theorem
    about legal input only, with no separate validity predicate to get wrong. -/
inductive Node where
  /-- A bare scalar. -/
  | plain
  /-- One property, then content — `&a b`. -/
  | propped
  /-- A block collection wrapping a node.  **Opens virtually.** -/
  | block (inner : Node)
  /-- A property on a block collection — `&a` then a virtual open, then `inner`.
      This is `&mapping⏎&key …`: the anchor is on the MAPPING. -/
  | proppedBlock (inner : Node)
  /-- A flow collection wrapping a node — `[ inner`. -/
  | flow (inner : Node)
  /-- A property on a flow collection — `&a [ inner`. -/
  | proppedFlow (inner : Node)
  deriving Repr

/-- The token stream a document scans to.  The one asymmetry that matters:
    `block` contributes **no** token of its own, `flow` contributes `openFlowT`. -/
def emit : Node → List Tok
  | .plain => [.contentT]
  | .propped => [.propT, .contentT]
  | .block inner => emit inner
  | .proppedBlock inner => .propT :: emit inner
  | .flow inner => .openFlowT :: emit inner
  | .proppedFlow inner => .propT :: .openFlowT :: emit inner

/-- Does this document contain a collection that opens without a token?  This is
    the toy of "is the scanner in block context anywhere in here". -/
def hasVirtualOpen : Node → Bool
  | .plain => false
  | .propped => false
  | .block _ => true
  | .proppedBlock _ => true
  | .flow inner => hasVirtualOpen inner
  | .proppedFlow inner => hasVirtualOpen inner

/-- **The proxy.**  Two property tokens next to each other — what a guard reads
    as "a second property on the same node".  Written with an explicit two-cell
    window rather than overlapping patterns so its equations are `simp`-usable. -/
def adjacentProps : List Tok → Bool
  | [] => false
  | [_] => false
  | a :: b :: rest => (a == .propT && b == .propT) || adjacentProps (b :: rest)

/-! ## §2  Where the proxy is exact

No virtual open ⇒ adjacency really does mean "same property run", so a guard
that rejects on it rejects nothing legal. -/

private theorem adjacentProps_cons_nonProp (t : Tok) (h : t ≠ .propT) (l : List Tok) :
    adjacentProps (t :: l) = adjacentProps l := by
  cases l with
  | nil => rfl
  | cons b rest => simp [adjacentProps, h]

theorem adjacency_exact_without_virtual_open (n : Node) (h : hasVirtualOpen n = false) :
    adjacentProps (emit n) = false := by
  induction n with
  | plain => rfl
  | propped => rfl
  | block _ _ => simp [hasVirtualOpen] at h
  | proppedBlock _ _ => simp [hasVirtualOpen] at h
  | flow inner ih =>
    show adjacentProps (Tok.openFlowT :: emit inner) = false
    rw [adjacentProps_cons_nonProp _ (by decide)]
    exact ih (by simpa [hasVirtualOpen] using h)
  | proppedFlow inner ih =>
    have hin : adjacentProps (Tok.openFlowT :: emit inner) = false := by
      rw [adjacentProps_cons_nonProp _ (by decide)]
      exact ih (by simpa [hasVirtualOpen] using h)
    show adjacentProps (Tok.propT :: Tok.openFlowT :: emit inner) = false
    simp only [adjacentProps, hin]
    decide

/-- The contrapositive a guard actually uses: inside a flow, the token pattern
    the guard rejects is emitted by **no** legal document, so rejecting it is
    free. -/
theorem no_flow_document_emits_adjacent_props (n : Node) (h : hasVirtualOpen n = false) :
    adjacentProps (emit n) ≠ true := by
  rw [adjacency_exact_without_virtual_open n h]; simp

/-! ## §3  Where it is not

The witness is small, and it is not degenerate — it is the ordinary shape
"property on a collection, whose first member also carries a property". -/

/-- `&a` on a block collection whose inner node is `&b c`. -/
def theCounterexample : Node := .proppedBlock .propped

/-- Its token stream is exactly the pattern the guard rejects. -/
theorem counterexample_emits_the_pattern :
    emit theCounterexample = [.propT, .propT, .contentT] := rfl

/-- **The proxy fires on a legal document.**  `theCounterexample` inhabits
    `Node`, so it is legal by construction; the ungated guard rejects it. -/
theorem adjacency_fires_on_a_legal_document :
    adjacentProps (emit theCounterexample) = true := by decide

/-- And the two facts are not in tension: the document has a virtual open, which
    is exactly the hypothesis §2 needed. -/
theorem counterexample_has_a_virtual_open :
    hasVirtualOpen theCounterexample = true := rfl

/-! ## §4  The guard pair, and the blast radius of gating it -/

/-- What the guard sees when a property arrives: the context, and whether the
    previous token was a property. -/
structure St where
  /-- Is the scanner inside a flow collection? -/
  inFlow : Bool
  /-- Was the last real token a property? -/
  lastProp : Bool
  deriving DecidableEq, Repr

/-- The first version: reject on adjacency, everywhere. -/
def guardUngated (s : St) : Bool := s.lastProp

/-- The shipped version: reject on adjacency, but only where the proxy is exact. -/
def guardGated (s : St) : Bool := s.inFlow && s.lastProp

/-- Gating costs **nothing** where the proxy was sound: inside a flow the two
    guards are the same function. -/
theorem guards_agree_in_flow (s : St) (h : s.inFlow = true) :
    guardUngated s = guardGated s := by
  obtain ⟨f, l⟩ := s; cases f <;> cases l <;> simp_all [guardUngated, guardGated]

/-- And they differ on exactly one class — block context with a property behind
    us — which is nonempty, so the gate is a real weakening and not decoration. -/
theorem guards_differ_exactly_in_block (s : St) :
    (guardUngated s ≠ guardGated s) ↔ (s.inFlow = false ∧ s.lastProp = true) := by
  obtain ⟨f, l⟩ := s; cases f <;> cases l <;> simp [guardUngated, guardGated]

/-! ## §5  Why the hand-built probe list could not have found it

`handProbe` is what gets written while thinking about a flow-context guard:
every entry is flow-shaped.  `handProbe_has_no_virtual_open` is the reason its
silence is worthless — by §2 those cases *cannot* trip the proxy, so the sweep
was answering a question it had already assumed away. -/

/-- The cases one writes while thinking about the guard. -/
def handProbe : List Node :=
  [ .plain, .propped,
    .flow .plain, .flow .propped,
    .proppedFlow .plain, .proppedFlow .propped,
    .flow (.flow .propped), .proppedFlow (.flow .propped) ]

/-- The cases a regression corpus contains because it was collected for other
    reasons entirely. -/
def corpus : List Node :=
  handProbe ++
  [ .block .plain, .block .propped,
    .proppedBlock .plain,
    .proppedBlock .propped,          -- `&mapping⏎&key …`
    .block (.proppedBlock .propped),
    .proppedBlock (.flow .propped) ]

/-! Every hand-written case is flow-shaped … -/
#guard handProbe.all (fun n => !hasVirtualOpen n)

/-! … so the sweep is silent, necessarily and not by luck (§2). -/
#guard handProbe.all (fun n => !adjacentProps (emit n))

/-! The corpus is not, … -/
#guard corpus.any (fun n => hasVirtualOpen n)

/-! … and it refutes the ungated guard on the first run. -/
#guard corpus.any (fun n => adjacentProps (emit n))

/-! Exactly two corpus entries refute it — small enough to read, which is what
    makes the corpus a usable diagnostic and not just a red build. -/
#guard (corpus.filter (fun n => adjacentProps (emit n))).length == 2

/-! The gated guard accepts every corpus entry that the proxy should not have
    touched: no legal document without a virtual open trips it. -/
#guard corpus.all (fun n => hasVirtualOpen n || !adjacentProps (emit n))

/-! ## §6  Axiom profile -/

/-- info: 'Tests.Reflections.AdjacencyProxyAndVirtualStructure.adjacency_exact_without_virtual_open' depends on axioms: [propext] -/
#guard_msgs in
#print axioms adjacency_exact_without_virtual_open

/-- info: 'Tests.Reflections.AdjacencyProxyAndVirtualStructure.adjacency_fires_on_a_legal_document' does not depend on any axioms -/
#guard_msgs in
#print axioms adjacency_fires_on_a_legal_document

/-- info: 'Tests.Reflections.AdjacencyProxyAndVirtualStructure.guards_differ_exactly_in_block' depends on axioms: [propext] -/
#guard_msgs in
#print axioms guards_differ_exactly_in_block

end Tests.Reflections.AdjacencyProxyAndVirtualStructure
